<head>
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
<!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">-->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<style>
    /*! CSS Used from: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css */
    img{border:0;}
    button,input{margin:0;font:inherit;color:inherit;}
    button{overflow:visible;}
    button{text-transform:none;}
    button{-webkit-appearance:button;cursor:pointer;}
    button::-moz-focus-inner,input::-moz-focus-inner{padding:0;border:0;}
    input{line-height:normal;}
    input[type=checkbox]{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0;}
    table{border-spacing:0;border-collapse:collapse;}
    td,th{padding:0;}
    @media print{
        *,:after,:before{color:#000!important;text-shadow:none!important;background:0 0!important;-webkit-box-shadow:none!important;box-shadow:none!important;}
        thead{display:table-header-group;}
        img,tr{page-break-inside:avoid;}
        img{max-width:100%!important;}
        .table{border-collapse:collapse!important;}
        .table td,.table th{background-color:#fff!important;}
    }
    *{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;}
    :after,:before{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;}
    button,input{font-family:inherit;font-size:inherit;line-height:inherit;}
    img{vertical-align:middle;}
    .text-center{text-align:center;}
    .text-warning{color:#8a6d3b;}
    .text-danger{color:#a94442;}
    .container-fluid{padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;}
    .row{margin-right:-15px;margin-left:-15px;}
    .col-lg-2,.col-lg-4,.col-lg-5,.col-lg-8,.col-md-4,.col-md-8,.col-sm-12,.col-xs-12{position:relative;min-height:1px;padding-right:15px;padding-left:15px;}
    .col-xs-12{float:left;}
    .col-xs-12{width:100%;}
    @media (min-width:768px){
        .col-sm-12{float:left;}
        .col-sm-12{width:100%;}
    }
    @media (min-width:992px){
        .col-md-4,.col-md-8{float:left;}
        .col-md-8{width:66.66666667%;}
        .col-md-4{width:33.33333333%;}
    }
    @media (min-width:1200px){
        .col-lg-2,.col-lg-4,.col-lg-5,.col-lg-8{float:left;}
        .col-lg-8{width:66.66666667%;}
        .col-lg-5{width:41.66666667%;}
        .col-lg-4{width:33.33333333%;}
        .col-lg-2{width:16.66666667%;}
    }
    table{background-color:transparent;}
    th{text-align:left;}
    .table{width:100%;max-width:100%;margin-bottom:20px;}
    .table>tbody>tr>td,.table>thead>tr>th{padding:8px;line-height:1.42857143;vertical-align:top;border-top:1px solid #ddd;}
    .table>thead>tr>th{vertical-align:bottom;border-bottom:2px solid #ddd;}
    .table>thead:first-child>tr:first-child>th{border-top:0;}
    .table-hover>tbody>tr:hover{background-color:#f5f5f5;}
    .table-responsive{min-height:.01%;overflow-x:auto;}
    @media screen and (max-width:767px){
        .table-responsive{width:100%;margin-bottom:15px;overflow-y:hidden;-ms-overflow-style:-ms-autohiding-scrollbar;border:1px solid #ddd;}
        .table-responsive>.table{margin-bottom:0;}
        .table-responsive>.table>tbody>tr>td,.table-responsive>.table>thead>tr>th{white-space:nowrap;}
    }
    input[type=checkbox]{margin:4px 0 0;margin-top:1px\9;line-height:normal;}
    input[type=checkbox]:focus{outline:5px auto -webkit-focus-ring-color;outline-offset:-2px;}
    .btn{display:inline-block;padding:6px 12px;margin-bottom:0;font-size:14px;font-weight:400;line-height:1.42857143;text-align:center;white-space:nowrap;vertical-align:middle;-ms-touch-action:manipulation;touch-action:manipulation;cursor:pointer;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;background-image:none;border:1px solid transparent;border-radius:4px;}
    .btn:active:focus,.btn:focus{outline:5px auto -webkit-focus-ring-color;outline-offset:-2px;}
    .btn:focus,.btn:hover{color:#333;text-decoration:none;}
    .btn:active{background-image:none;outline:0;-webkit-box-shadow:inset 0 3px 5px rgba(0,0,0,.125);box-shadow:inset 0 3px 5px rgba(0,0,0,.125);}
    .btn-success{color:#fff;background-color:#5cb85c;border-color:#4cae4c;}
    .btn-success:focus{color:#fff;background-color:#449d44;border-color:#255625;}
    .btn-success:hover{color:#fff;background-color:#449d44;border-color:#398439;}
    .btn-success:active{color:#fff;background-color:#449d44;border-color:#398439;}
    .btn-success:active:focus,.btn-success:active:hover{color:#fff;background-color:#398439;border-color:#255625;}
    .btn-success:active{background-image:none;}
    .btn-danger{color:#fff;background-color:#d9534f;border-color:#d43f3a;}
    .btn-danger:focus{color:#fff;background-color:#c9302c;border-color:#761c19;}
    .btn-danger:hover{color:#fff;background-color:#c9302c;border-color:#ac2925;}
    .btn-danger:active{color:#fff;background-color:#c9302c;border-color:#ac2925;}
    .btn-danger:active:focus,.btn-danger:active:hover{color:#fff;background-color:#ac2925;border-color:#761c19;}
    .btn-danger:active{background-image:none;}
    .btn-xs{padding:1px 5px;font-size:12px;line-height:1.5;border-radius:3px;}
    .btn-group{position:relative;display:inline-block;vertical-align:middle;}
    .btn-group>.btn{position:relative;float:left;}
    .btn-group>.btn:active,.btn-group>.btn:focus,.btn-group>.btn:hover{z-index:2;}
    .btn-group .btn+.btn{margin-left:-1px;}
    .btn-group>.btn:first-child{margin-left:0;}
    .btn-group>.btn:first-child:not(:last-child):not(.dropdown-toggle){border-top-right-radius:0;border-bottom-right-radius:0;}
    .btn-group>.btn:last-child:not(:first-child){border-top-left-radius:0;border-bottom-left-radius:0;}
    .alert{padding:15px;margin-bottom:20px;border:1px solid transparent;border-radius:4px;}
    .alert-info{color:#31708f;background-color:#d9edf7;border-color:#bce8f1;}
    .alert-warning{color:#8a6d3b;background-color:#fcf8e3;border-color:#faebcc;}
    .alert-danger{color:#a94442;background-color:#f2dede;border-color:#ebccd1;}
    .container-fluid:after,.container-fluid:before,.row:after,.row:before{display:table;content:" ";}
    .container-fluid:after,.row:after{clear:both;}
    .pull-left{float:left!important;}
    /*! CSS Used from: https://use.fontawesome.com/releases/v5.2.0/css/all.css */
    .far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;text-rendering:auto;line-height:1;}
    .fa-check-square:before{content:"\f14a";}
    .fa-exclamation-circle:before{content:"\f06a";}
    .fa-exclamation-triangle:before{content:"\f071";}
    .fa-info:before{content:"\f129";}
    .fa-sync-alt:before{content:"\f2f1";}
    .fa-times:before{content:"\f00d";}
    .fa-times-circle:before{content:"\f057";}
    .fa-trash-alt:before{content:"\f2ed";}
    .fa-info-circle:before{content:"\f05a";}
    .far{font-weight:400;}
    .far,.fas{font-family:"Font Awesome 5 Free";}
    .fas{font-weight:900;}
    /*! CSS Used from: Embedded */
    .container-fluid{max-width:100%;}
    .mar-top-btt-80{margin-bottom:80px;margin-top:80px;}
    .max-w-100{max-width:100%;}
    .mar-10{margin:10px;}
    .pad-10{padding:10px;}
    .pad-40{padding:40px;}
    .min-hei-400{min-height:400px;}
    table{font-size:14px;width:100%!important;display:inline-block;word-wrap:break-word;}
    table td{word-wrap:break-word;}
    .table-responsive{display:table;}s
    .forinfo span{font-size:14px;}
    .btn{border-radius:0!important;font-size:14px;font-weight:400;}
    .btn-success{background:#4cb58e;}
    .btn-success:hover{background:#53c79c;}
    .out-box{max-height:600px;overflow-x:auto;overflow-y:auto;padding:15px;}
    @media only screen and (max-width:800px){
        .pad-40{padding:0;}
        .mar-top-btt-80{margin-bottom:40px;margin-top:40px;}
    }
    /*! CSS Used from: https://use.fontawesome.com/releases/v5.2.0/css/all.css */
    .far,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;font-variant:normal;text-rendering:auto;line-height:1;}
    .fa-check-square:before{content:"\f14a";}
    .fa-exclamation-circle:before{content:"\f06a";}
    .fa-exclamation-triangle:before{content:"\f071";}
    .fa-info:before{content:"\f129";}
    .fa-sync-alt:before{content:"\f2f1";}
    .fa-times:before{content:"\f00d";}
    .fa-times-circle:before{content:"\f057";}
    .fa-trash-alt:before{content:"\f2ed";}
    .far{font-weight:400;}
    .far,.fas{font-family:"Font Awesome 5 Free";}
    .fas{font-weight:900;}
    /*! CSS Used from: Embedded */
    .container-fluid{max-width:100%;}
    .mar-top-btt-80{margin-bottom:80px;margin-top:80px;}
    .max-w-100{max-width:100%;}
    .mar-10{margin:10px;}
    .pad-10{padding:10px;}
    .pad-40{padding:40px;}
    .min-hei-400{min-height:400px;}
    table{font-size:14px;width:100%!important;display:inline-block;word-wrap:break-word;}
    table td{word-wrap:break-word;}
    .table-active{background-color:rgba(0,0,0,.075);}
    .table-responsive{display:table;}
    .forinfo span{font-size:14px;}
    .alert{padding:7px;border:0;border-radius:0;}
    .alert-info{color:#31708f;background-color:#d9edf7;border-color:#bce8f1}
    .btn{border-radius:0!important;font-size:14px;font-weight:400;}
    .btn-success{background:#4cb58e;}
    .btn-success:hover{background:#53c79c;}
    .out-box{max-height:600px;overflow-x:auto;overflow-y:auto;padding:15px;}
    #showlog span{margin:2px 0;font-size:12px;word-wrap:break-word;}
    @media only screen and (max-width:800px){
        .pad-40{padding:0;}
        .mar-top-btt-80{margin-bottom:40px;margin-top:40px;}
    }
    /*! CSS Used fontfaces */
    @font-face{font-family:"Font Awesome 5 Free";font-style:normal;font-weight:400;src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.eot);src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.eot#iefix) format("embedded-opentype"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.woff2) format("woff2"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.woff) format("woff"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.ttf) format("truetype"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.svg#fontawesome) format("svg");}
    @font-face{font-family:"Font Awesome 5 Free";font-style:normal;font-weight:900;src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.eot);src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.eot#iefix) format("embedded-opentype"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.woff2) format("woff2"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.woff) format("woff"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.ttf) format("truetype"),url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.svg#fontawesome) format("svg");}
    @font-face{font-family:"Font Awesome 5 Free";font-style:normal;font-weight:400;src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.eot);src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.eot#iefix) format("embedded-opentype") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.woff2) format("woff2") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.woff) format("woff") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.ttf) format("truetype") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-regular-400.svg#fontawesome) format("svg");}
    @font-face{font-family:"Font Awesome 5 Free";font-style:normal;font-weight:900;src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.eot);src:url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.eot#iefix) format("embedded-opentype") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.woff2) format("woff2") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.woff) format("woff") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.ttf) format("truetype") , url(https://use.fontawesome.com/releases/v5.2.0/webfonts/fa-solid-900.svg#fontawesome) format("svg");}
</style>
<script>
    var showdebbug_url = "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>";
    console.log('showdebbug_url: '+showdebbug_url);
    var deletelogs_url = "<?php echo $block->getUrl('synccatalog/ajax/deletelogs'); ?>";
    console.log('deletelogs_url: '+deletelogs_url);
</script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2 col-md-4 col-sm-12 pad-10">
            <img alt="logo sales layer" src="<?php echo $this->getViewFileUrl('Saleslayer_Synccatalog::images/logo.svg'); ?>"/>
        </div>
        <div class="col-lg-5 col-md-4 col-xs-12 pad-10" id="slh1selector">
        </div>
        <div class="col-lg-5 col-md-4 col-xs-12 pad-10 forinfo" >
            <span class="pull-left" id="sllisted"></span><span class="pull-left" id="slwarnings"></span><span class="pull-left" id="slerrors"></span>
        </div>
    </div>
    <div class="row mar-top-btt-80">
        <div class="col-lg-4 col-md-4 col-sm-12">
            <div class="w-100 btn-group btn-group-toggle">
                <button type="button" class="btn btn-success btn-xs buttonscommandexecuter" title="Reload Logs" name="showlogfiles"><i class="fas fa-sync-alt"></i> Reload logs</button>
                <button type="button" class="btn btn-danger btn-xs buttonscommandexecuter" title="Delete logs" name="deletelogfile"><i class="fas fa-trash-alt"></i> Remove logs</button>
            </div>
            <div class="w-100 table-responsive">
                <table class="table table-hover w-100 max-w-100" id="tablelogs">
                    <thead>
                        <tr>
                            <th scope="col"><i class="far fa-check-square" id="selectall"></i></th>
                            <th scope="col">Name of log file</th>
                            <th scope="col">Lines</th>
                            <th scope="col" class="text-center"><i class="fas fa-exclamation-circle text-warning"></i></th>
                            <th scope="col" class="text-center"><i class="fas  fa-times-circle text-danger"></i></th>
                        </tr>
                    </thead>
                    <tbody id="listoflogs" >
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-12 pad-40 min-hei-400">
            <div id="showlog" class="w-100 min-hei-400 out-box" ></div>
        </div>
    </div>
</div>
<script>
    // require(['jquery','domReady!'],function($){
    //     $(document).ready(function() {
    //         function sync_custom_command(command) {
    //             var showdebbug_url = "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>";
    //             console.log('showdebbug_url: '+showdebbug_url);
    //             console.log('command: '+command);
    //             $('body').trigger('processStart');
    //                 $.ajax({
    //                     method: "POST",
    //                     url: "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>",
    //                     data: {'logcommand':command},
    //                     dataType: "json"
    //                 }).done(function (data_return) {
    //                     if(data_return['message_type'] === 'success'){
    //                         if(data_return['function'] === 'showlogfiles'){
    //                             if(data_return['content']['file'].length >= 1){
    //                                  document.getElementById('listoflogs').innerHTML = '';
    //                                  document.getElementById('showlog').innerHTML = '';
    //                                  //null info
    //                                 var listed = document.getElementById('sllisted');
    //                                 listed.innerHTML = '';
    //                                 listed.classList.remove("alert");
    //                                 listed.classList.remove("alert-info");
    //                                 //null warnings
    //                                 var warning = document.getElementById('slwarnings');
    //                                 warning.innerHTML = '';
    //                                 warning.classList.remove("alert");
    //                                 warning.classList.remove("alert-warning");
    //                                  //null errors
    //                                 var errors = document.getElementById('slerrors');
    //                                 errors.innerHTML = '';
    //                                 errors.classList.remove("alert");
    //                                 errors.classList.remove("alert-danger");

    //                                 var i;
    //                                 if(data_return['content']['file'].length >= 1){
    //                                     for (i=0; i < data_return['content']['file'].length ; i++ ){
    //                                         if(i === 0){
    //                                             sync_custom_command(data_return['content']['file'][i]);
    //                                         }
    //                                         var tr = document.createElement('tr');
    //                                         if(i === 0) {
    //                                             tr.setAttribute('class', 'filesnamestr table-active');
    //                                         }else{
    //                                             tr.setAttribute('class', 'filesnamestr');
    //                                         }
    //                                         var tdc = document.createElement('td');
    //                                         var chk = document.createElement('input');
    //                                             chk.setAttribute('type', 'checkbox');
    //                                             chk.setAttribute('name', 'file[]');
    //                                             chk.setAttribute('value', data_return['content']['file'][i]);
    //                                             tdc.appendChild(chk);

    //                                          var tdp = document.createElement('td');
    //                                              tdp.setAttribute('class', 'filesnames');
    //                                              tdp.setAttribute('data',  data_return['content']['file'][i]);

    //                                          var node = document.createTextNode(data_return['content']['file'][i]);

    //                                          var tdlines = document.createElement('td');
    //                                          var nodelines = document.createTextNode(data_return['content']['lines'][i]);
    //                                              tdlines.appendChild(nodelines);

    //                                         var tdwarnings = document.createElement('td');
    //                                         if(data_return['content']['warnings'][i] >= 1){
    //                                             var nodewarnings = document.createTextNode(data_return['content']['warnings'][i]);
    //                                             tdwarnings.setAttribute('class','text-center text-warning');
    //                                             tdwarnings.appendChild(nodewarnings);
    //                                         }

    //                                         var tderror = document.createElement('td');
    //                                         if(data_return['content']['errors'][i] >= 1){
    //                                             var nodeerror = document.createTextNode(data_return['content']['errors'][i]);
    //                                             tderror.setAttribute('class','text-center text-danger');
    //                                             tderror.appendChild(nodeerror);
    //                                         }
    //                                         tdp.appendChild(node);

    //                                         tr.appendChild(tdc);
    //                                         tr.appendChild(tdp);
    //                                         tr.appendChild(tdlines);
    //                                         tr.appendChild(tdwarnings);
    //                                         tr.appendChild(tderror);

    //                                         var parent = document.getElementById('listoflogs');
    //                                         parent.appendChild(tr);

    //                                         $(".filesnames").on("click",function(){
    //                                             document.getElementById('slh1selector').innerHTML = '';
    //                                             var commandfor = $(this).attr('data');
    //                                             sync_custom_command(commandfor);
    //                                             var h1 = document.createElement('h3');
    //                                             var div = document.getElementById('slh1selector');
    //                                             var node = document.createTextNode(commandfor);
    //                                             h1.appendChild(node);
    //                                             div.appendChild(h1);
    //                                         });
    //                                     }
    //                                 }
    //                                 $('body').trigger('processStop');
    //                             }
    //                         }else if(data_return['function'] === 'showlogfilecontent'){

    //                             var table = document.getElementById('listoflogs');
    //                             var trs = table.getElementsByClassName("filesnamestr");

    //                             for (var i = 0; i < trs.length; i++) {
    //                                 trs[i].addEventListener("click", function() {
    //                                     var current = document.getElementsByClassName("table-active");
    //                                     if (current.length > 0) {
    //                                         current[0].className = current[0].className.replace("table-active", "");
    //                                     }
    //                                     this.className += " table-active";
    //                                 });
    //                             }
    //                             $('body').trigger('processStop');
    //                             document.getElementById('showlog').innerHTML = data_return['content'];
    //                             //avisos de error
    //                             if(data_return['lines']>=1){
    //                                 var listed = document.getElementById('sllisted');
    //                                     listed.innerHTML = data_return['lines']+ ' Lines' ;
    //                                     listed.classList.add("alert");
    //                                     listed.classList.add("alert-info");
    //                                 var faicon = document.createElement('i');
    //                                     faicon.setAttribute('class','fas fa-info mar-10');
    //                                     listed.insertBefore(faicon,listed.childNodes[0]);

    //                             }else{
    //                                 var listed = document.getElementById('sllisted');
    //                                     listed.innerHTML = '';
    //                                     listed.classList.remove("alert");
    //                                     listed.classList.remove("alert-info");
    //                             }
    //                             if(data_return['warnings']>=1){
    //                                 var warning = document.getElementById('slwarnings');
    //                                     warning.innerHTML = data_return['warnings']+ ' Warnings';
    //                                     warning.classList.add("alert");
    //                                     warning.classList.add("alert-warning");
    //                                     warning.setAttribute('onclick',"window.location.href=\"#idwarning0\"");
    //                                 var faicon = document.createElement('i');
    //                                     faicon.setAttribute('class','fas fa-exclamation-triangle mar-10');
    //                                     warning.insertBefore(faicon,warning.childNodes[0]);

    //                             }else{
    //                                 var warning = document.getElementById('slwarnings');
    //                                     warning.innerHTML = '';
    //                                     warning.classList.remove("alert");
    //                                     warning.classList.remove("alert-warning");
    //                             }
    //                             if(data_return['errors']>=1){
    //                                 var errors = document.getElementById('slerrors');
    //                                     errors.innerHTML = data_return['errors']+ ' Errors';
    //                                     errors.classList.add("alert");
    //                                     errors.classList.add("alert-danger");
    //                                     errors.setAttribute('onclick',"window.location.href=\"#iderror0\"");
    //                                 var faicon = document.createElement('i');
    //                                     faicon.setAttribute('class','fas fa-times mar-10');
    //                                     errors.insertBefore(faicon,errors.childNodes[0]);
    //                             }else{
    //                                 var errors = document.getElementById('slerrors');
    //                                     errors.innerHTML = '';
    //                                     errors.classList.remove("alert");
    //                                     errors.classList.remove("alert-danger");
    //                             }
    //                         }
    //                     }else{
    //                         showMessage(data_return['message_type'],data_return['content']);
    //                         clear_message_status();
    //                     }
    //                 }).fail(function (data_return) {
    //                     console.log('Ajax connection error: ');
    //                     console.log(data_return);
    //                 }).always(function (){
    //                     $('body').trigger('processStop');
    //                 });
    //         }
    //         function files_for_delete(command) {
    //             $('body').trigger('processStart');
    //             $.ajax({
    //                 method: "POST",
    //                 url: "<?php echo $block->getUrl('synccatalog/ajax/deletelogs'); ?>",
    //                 data: {'logfilesfordelete':command},
    //                 dataType: "json"
    //             }).done(function (data_return) {
    //                 document.getElementById('listoflogs').innerHTML = '';
    //                 document.getElementById('showlog').innerHTML = '';
    //                 //null info
    //                 var listed = document.getElementById('sllisted');
    //                 listed.innerHTML = '';
    //                 listed.classList.remove("alert");
    //                 listed.classList.remove("alert-info");
    //                 //null warnings
    //                 var warning = document.getElementById('slwarnings');
    //                 warning.innerHTML = '';
    //                 warning.classList.remove("alert");
    //                 warning.classList.remove("alert-warning");
    //                 //null errors
    //                 var errors = document.getElementById('slerrors');
    //                 errors.innerHTML = '';
    //                 errors.classList.remove("alert");
    //                 errors.classList.remove("alert-danger");
    //                 document.getElementById('slh1selector').innerHTML = '';
    //                 if(data_return['message_type'] === 'success'){
    //                     $('body').trigger('processStop');
    //                     sync_custom_command('showlogfiles');
    //                 }
    //             }).fail(function (data_return) {
    //                 console.log('Ajax connection error delete logs');
    //                 clear_message_status();
    //             });
    //         }
    //         $("#selectall").on("click",function(){
    //             var aa = document.querySelectorAll("input[type=checkbox]");
    //             var first = true;
    //             for (var i = 0; i < aa.length; i++){
    //                 first = aa[i].checked;
    //                 if(first === false ){
    //                     aa[i].checked = true;
    //                 }else{
    //                     aa[i].checked = false;
    //                 }
    //             }
    //         });
    //         function showMessage(type = 'success', message) {
    //             if (document.contains(document.getElementById("messages"))) {
    //                 document.getElementById("messages").remove();
    //             }
    //             var elm = document.createElement('div');
    //             elm.setAttribute('id', 'messages');
    //             var subdiv = document.createElement('div');
    //             subdiv.setAttribute('class', 'messages');

    //             var submessage = document.createElement('div');
    //             submessage.setAttribute('class', 'message message-' + type + ' ' + type);

    //             var subdivmessage = document.createElement('div');
    //             subdivmessage.setAttribute('data-ui-id', 'messages-message-' + type);

    //             var node = document.createTextNode(message);

    //             subdivmessage.appendChild(node);
    //             submessage.appendChild(subdivmessage);
    //             subdiv.appendChild(submessage);
    //             elm.appendChild(subdiv);

    //             var parent = document.getElementById('anchor-content');
    //             parent.insertBefore(elm, parent.lastChild);
    //         }
    //         function clear_message_status() {
    //             var timeout = setTimeout(function () {
    //                 if (document.contains(document.getElementById("messages"))) {
    //                     document.getElementById("messages").remove();
    //                 }
    //                 clearTimeout(timeout);
    //             }, 7000);
    //         }
    //         $(".buttonscommandexecuter").on("click",function(){
    //              var command = this.name;
    //              console.log('command en buttonscommandexecuter: '+command);
    //             // sync_custom_command('showlogfiles');
    //              if(command === 'deletelogfile'){
    //                  var  array = [];
    //                  var checkboxes = document.querySelectorAll('input[type=checkbox]:checked');
    //                  for (var i = 0; i < checkboxes.length; i++) {
    //                      array.push(checkboxes[i].value)
    //                  }
    //                  if(array.length >=1){
    //                      files_for_delete(array);
    //                  }
    //              }else{
    //                  sync_custom_command(command);
    //              }
    //          });

    //         sync_custom_command('showlogfiles');
    //         // console.log('documento ready');
    //     });
    // })

    // require([
    //     'jquery',
    //     'domReady!'// wait for dom ready
    // ], function ($) {

    // require([
    //     'jquery', 'domReady'
    // ], function ($) {
    //     function sync_custom_command(command) {
    //         var showdebbug_url = "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>";
    //         console.log('showdebbug_url: '+showdebbug_url);
    //         console.log('command: '+command);
    //         $('body').trigger('processStart');
    //             $.ajax({
    //                 method: "POST",
    //                 url: "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>",
    //                 data: {'logcommand':command},
    //                 dataType: "json"
    //             }).done(function (data_return) {
    //                 if(data_return['message_type'] === 'success'){
    //                     if(data_return['function'] === 'showlogfiles'){
    //                         if(data_return['content']['file'].length >= 1){
    //                              document.getElementById('listoflogs').innerHTML = '';
    //                              document.getElementById('showlog').innerHTML = '';
    //                              //null info
    //                             var listed = document.getElementById('sllisted');
    //                             listed.innerHTML = '';
    //                             listed.classList.remove("alert");
    //                             listed.classList.remove("alert-info");
    //                             //null warnings
    //                             var warning = document.getElementById('slwarnings');
    //                             warning.innerHTML = '';
    //                             warning.classList.remove("alert");
    //                             warning.classList.remove("alert-warning");
    //                              //null errors
    //                             var errors = document.getElementById('slerrors');
    //                             errors.innerHTML = '';
    //                             errors.classList.remove("alert");
    //                             errors.classList.remove("alert-danger");

    //                             var i;
    //                             if(data_return['content']['file'].length >= 1){
    //                                 for (i=0; i < data_return['content']['file'].length ; i++ ){
    //                                     if(i === 0){
    //                                         sync_custom_command(data_return['content']['file'][i]);
    //                                     }
    //                                     var tr = document.createElement('tr');
    //                                     if(i === 0) {
    //                                         tr.setAttribute('class', 'filesnamestr table-active');
    //                                     }else{
    //                                         tr.setAttribute('class', 'filesnamestr');
    //                                     }
    //                                     var tdc = document.createElement('td');
    //                                     var chk = document.createElement('input');
    //                                         chk.setAttribute('type', 'checkbox');
    //                                         chk.setAttribute('name', 'file[]');
    //                                         chk.setAttribute('value', data_return['content']['file'][i]);
    //                                         tdc.appendChild(chk);

    //                                      var tdp = document.createElement('td');
    //                                          tdp.setAttribute('class', 'filesnames');
    //                                          tdp.setAttribute('data',  data_return['content']['file'][i]);

    //                                      var node = document.createTextNode(data_return['content']['file'][i]);

    //                                      var tdlines = document.createElement('td');
    //                                      var nodelines = document.createTextNode(data_return['content']['lines'][i]);
    //                                          tdlines.appendChild(nodelines);

    //                                     var tdwarnings = document.createElement('td');
    //                                     if(data_return['content']['warnings'][i] >= 1){
    //                                         var nodewarnings = document.createTextNode(data_return['content']['warnings'][i]);
    //                                         tdwarnings.setAttribute('class','text-center text-warning');
    //                                         tdwarnings.appendChild(nodewarnings);
    //                                     }

    //                                     var tderror = document.createElement('td');
    //                                     if(data_return['content']['errors'][i] >= 1){
    //                                         var nodeerror = document.createTextNode(data_return['content']['errors'][i]);
    //                                         tderror.setAttribute('class','text-center text-danger');
    //                                         tderror.appendChild(nodeerror);
    //                                     }
    //                                     tdp.appendChild(node);

    //                                     tr.appendChild(tdc);
    //                                     tr.appendChild(tdp);
    //                                     tr.appendChild(tdlines);
    //                                     tr.appendChild(tdwarnings);
    //                                     tr.appendChild(tderror);

    //                                     var parent = document.getElementById('listoflogs');
    //                                     parent.appendChild(tr);

    //                                     $(".filesnames").on("click",function(){
    //                                         document.getElementById('slh1selector').innerHTML = '';
    //                                         var commandfor = $(this).attr('data');
    //                                         sync_custom_command(commandfor);
    //                                         var h1 = document.createElement('h3');
    //                                         var div = document.getElementById('slh1selector');
    //                                         var node = document.createTextNode(commandfor);
    //                                         h1.appendChild(node);
    //                                         div.appendChild(h1);
    //                                     });
    //                                 }
    //                             }
    //                             $('body').trigger('processStop');
    //                         }
    //                     }else if(data_return['function'] === 'showlogfilecontent'){

    //                         var table = document.getElementById('listoflogs');
    //                         var trs = table.getElementsByClassName("filesnamestr");

    //                         for (var i = 0; i < trs.length; i++) {
    //                             trs[i].addEventListener("click", function() {
    //                                 var current = document.getElementsByClassName("table-active");
    //                                 if (current.length > 0) {
    //                                     current[0].className = current[0].className.replace("table-active", "");
    //                                 }
    //                                 this.className += " table-active";
    //                             });
    //                         }
    //                         $('body').trigger('processStop');
    //                         document.getElementById('showlog').innerHTML = data_return['content'];
    //                         //avisos de error
    //                         if(data_return['lines']>=1){
    //                             var listed = document.getElementById('sllisted');
    //                                 listed.innerHTML = data_return['lines']+ ' Lines' ;
    //                                 listed.classList.add("alert");
    //                                 listed.classList.add("alert-info");
    //                             var faicon = document.createElement('i');
    //                                 faicon.setAttribute('class','fas fa-info mar-10');
    //                                 listed.insertBefore(faicon,listed.childNodes[0]);

    //                         }else{
    //                             var listed = document.getElementById('sllisted');
    //                                 listed.innerHTML = '';
    //                                 listed.classList.remove("alert");
    //                                 listed.classList.remove("alert-info");
    //                         }
    //                         if(data_return['warnings']>=1){
    //                             var warning = document.getElementById('slwarnings');
    //                                 warning.innerHTML = data_return['warnings']+ ' Warnings';
    //                                 warning.classList.add("alert");
    //                                 warning.classList.add("alert-warning");
    //                                 warning.setAttribute('onclick',"window.location.href=\"#idwarning0\"");
    //                             var faicon = document.createElement('i');
    //                                 faicon.setAttribute('class','fas fa-exclamation-triangle mar-10');
    //                                 warning.insertBefore(faicon,warning.childNodes[0]);

    //                         }else{
    //                             var warning = document.getElementById('slwarnings');
    //                                 warning.innerHTML = '';
    //                                 warning.classList.remove("alert");
    //                                 warning.classList.remove("alert-warning");
    //                         }
    //                         if(data_return['errors']>=1){
    //                             var errors = document.getElementById('slerrors');
    //                                 errors.innerHTML = data_return['errors']+ ' Errors';
    //                                 errors.classList.add("alert");
    //                                 errors.classList.add("alert-danger");
    //                                 errors.setAttribute('onclick',"window.location.href=\"#iderror0\"");
    //                             var faicon = document.createElement('i');
    //                                 faicon.setAttribute('class','fas fa-times mar-10');
    //                                 errors.insertBefore(faicon,errors.childNodes[0]);
    //                         }else{
    //                             var errors = document.getElementById('slerrors');
    //                                 errors.innerHTML = '';
    //                                 errors.classList.remove("alert");
    //                                 errors.classList.remove("alert-danger");
    //                         }
    //                     }
    //                 }else{
    //                     showMessage(data_return['message_type'],data_return['content']);
    //                     clear_message_status();
    //                 }
    //             }).fail(function (data_return) {
    //                 console.log('Ajax connection error: ');
    //                 console.log(data_return);
    //             }).always(function (){
    //                 $('body').trigger('processStop');
    //             });
    //     }
    //     function files_for_delete(command) {
    //         $('body').trigger('processStart');
    //         $.ajax({
    //             method: "POST",
    //             url: "<?php echo $block->getUrl('synccatalog/ajax/deletelogs'); ?>",
    //             data: {'logfilesfordelete':command},
    //             dataType: "json"
    //         }).done(function (data_return) {
    //             document.getElementById('listoflogs').innerHTML = '';
    //             document.getElementById('showlog').innerHTML = '';
    //             //null info
    //             var listed = document.getElementById('sllisted');
    //             listed.innerHTML = '';
    //             listed.classList.remove("alert");
    //             listed.classList.remove("alert-info");
    //             //null warnings
    //             var warning = document.getElementById('slwarnings');
    //             warning.innerHTML = '';
    //             warning.classList.remove("alert");
    //             warning.classList.remove("alert-warning");
    //             //null errors
    //             var errors = document.getElementById('slerrors');
    //             errors.innerHTML = '';
    //             errors.classList.remove("alert");
    //             errors.classList.remove("alert-danger");
    //             document.getElementById('slh1selector').innerHTML = '';
    //             if(data_return['message_type'] === 'success'){
    //                 $('body').trigger('processStop');
    //                 sync_custom_command('showlogfiles');
    //             }
    //         }).fail(function (data_return) {
    //             console.log('Ajax connection error delete logs');
    //             clear_message_status();
    //         });
    //     }
    //     $("#selectall").on("click",function(){
    //         var aa = document.querySelectorAll("input[type=checkbox]");
    //         var first = true;
    //         for (var i = 0; i < aa.length; i++){
    //             first = aa[i].checked;
    //             if(first === false ){
    //                 aa[i].checked = true;
    //             }else{
    //                 aa[i].checked = false;
    //             }
    //         }
    //     });
    //     function showMessage(type = 'success', message) {
    //         if (document.contains(document.getElementById("messages"))) {
    //             document.getElementById("messages").remove();
    //         }
    //         var elm = document.createElement('div');
    //         elm.setAttribute('id', 'messages');
    //         var subdiv = document.createElement('div');
    //         subdiv.setAttribute('class', 'messages');

    //         var submessage = document.createElement('div');
    //         submessage.setAttribute('class', 'message message-' + type + ' ' + type);

    //         var subdivmessage = document.createElement('div');
    //         subdivmessage.setAttribute('data-ui-id', 'messages-message-' + type);

    //         var node = document.createTextNode(message);

    //         subdivmessage.appendChild(node);
    //         submessage.appendChild(subdivmessage);
    //         subdiv.appendChild(submessage);
    //         elm.appendChild(subdiv);

    //         var parent = document.getElementById('anchor-content');
    //         parent.insertBefore(elm, parent.lastChild);
    //     }
    //     function clear_message_status() {
    //         var timeout = setTimeout(function () {
    //             if (document.contains(document.getElementById("messages"))) {
    //                 document.getElementById("messages").remove();
    //             }
    //             clearTimeout(timeout);
    //         }, 7000);
    //     }
    //     $(".buttonscommandexecuter").on("click",function(){
    //          var command = this.name;
    //          console.log('command en buttonscommandexecuter: '+command);
    //         // sync_custom_command('showlogfiles');
    //          if(command === 'deletelogfile'){
    //              var  array = [];
    //              var checkboxes = document.querySelectorAll('input[type=checkbox]:checked');
    //              for (var i = 0; i < checkboxes.length; i++) {
    //                  array.push(checkboxes[i].value)
    //              }
    //              if(array.length >=1){
    //                  files_for_delete(array);
    //              }
    //          }else{
    //              sync_custom_command(command);
    //          }
    //      });

    //     // sync_custom_command('showlogfiles');
    //     // console.log('documento ready');

    // // });
    //     $(document).ready(function() {

    //         console.log('$ document. ready cargado');
    //         sync_custom_command('showlogfiles');
    //     })
    // }/*,function (domReady) {
    //     domReady(function () {
            
    //         // console.log('poteito potato');
    //         console.log('domReady cargado');
    //         // sync_custom_command('showlogfiles');

    //     })
    // },*/
    
    // );

    // require(['jquery','domReady'], function (domReady) {
    //     domReady(function () {
            
    //         // console.log('poteito potato');

    //         sync_custom_command('showlogfiles');

    //     });
    // });


    // require(['jquery', 'jquery/ui'], function($){ 
    //     $( document ).ready(function() {

    //         function sync_custom_command(command) {
    //             var showdebbug_url = "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>";
    //             console.log('showdebbug_url: '+showdebbug_url);
    //             console.log('command: '+command);
    //             $('body').trigger('processStart');
    //                 $.ajax({
    //                     method: "POST",
    //                     url: "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>",
    //                     data: {'logcommand':command},
    //                     dataType: "json"
    //                 }).done(function (data_return) {
    //                     console.log('done');
    //                     // if(data_return['message_type'] === 'success'){
    //                     //     if(data_return['function'] === 'showlogfiles'){
    //                     //         if(data_return['content']['file'].length >= 1){
    //                     //              document.getElementById('listoflogs').innerHTML = '';
    //                     //              document.getElementById('showlog').innerHTML = '';
    //                     //              //null info
    //                     //             var listed = document.getElementById('sllisted');
    //                     //             listed.innerHTML = '';
    //                     //             listed.classList.remove("alert");
    //                     //             listed.classList.remove("alert-info");
    //                     //             //null warnings
    //                     //             var warning = document.getElementById('slwarnings');
    //                     //             warning.innerHTML = '';
    //                     //             warning.classList.remove("alert");
    //                     //             warning.classList.remove("alert-warning");
    //                     //              //null errors
    //                     //             var errors = document.getElementById('slerrors');
    //                     //             errors.innerHTML = '';
    //                     //             errors.classList.remove("alert");
    //                     //             errors.classList.remove("alert-danger");

    //                     //             var i;
    //                     //             if(data_return['content']['file'].length >= 1){
    //                     //                 for (i=0; i < data_return['content']['file'].length ; i++ ){
    //                     //                     if(i === 0){
    //                     //                         sync_custom_command(data_return['content']['file'][i]);
    //                     //                     }
    //                     //                     var tr = document.createElement('tr');
    //                     //                     if(i === 0) {
    //                     //                         tr.setAttribute('class', 'filesnamestr table-active');
    //                     //                     }else{
    //                     //                         tr.setAttribute('class', 'filesnamestr');
    //                     //                     }
    //                     //                     var tdc = document.createElement('td');
    //                     //                     var chk = document.createElement('input');
    //                     //                         chk.setAttribute('type', 'checkbox');
    //                     //                         chk.setAttribute('name', 'file[]');
    //                     //                         chk.setAttribute('value', data_return['content']['file'][i]);
    //                     //                         tdc.appendChild(chk);

    //                     //                      var tdp = document.createElement('td');
    //                     //                          tdp.setAttribute('class', 'filesnames');
    //                     //                          tdp.setAttribute('data',  data_return['content']['file'][i]);

    //                     //                      var node = document.createTextNode(data_return['content']['file'][i]);

    //                     //                      var tdlines = document.createElement('td');
    //                     //                      var nodelines = document.createTextNode(data_return['content']['lines'][i]);
    //                     //                          tdlines.appendChild(nodelines);

    //                     //                     var tdwarnings = document.createElement('td');
    //                     //                     if(data_return['content']['warnings'][i] >= 1){
    //                     //                         var nodewarnings = document.createTextNode(data_return['content']['warnings'][i]);
    //                     //                         tdwarnings.setAttribute('class','text-center text-warning');
    //                     //                         tdwarnings.appendChild(nodewarnings);
    //                     //                     }

    //                     //                     var tderror = document.createElement('td');
    //                     //                     if(data_return['content']['errors'][i] >= 1){
    //                     //                         var nodeerror = document.createTextNode(data_return['content']['errors'][i]);
    //                     //                         tderror.setAttribute('class','text-center text-danger');
    //                     //                         tderror.appendChild(nodeerror);
    //                     //                     }
    //                     //                     tdp.appendChild(node);

    //                     //                     tr.appendChild(tdc);
    //                     //                     tr.appendChild(tdp);
    //                     //                     tr.appendChild(tdlines);
    //                     //                     tr.appendChild(tdwarnings);
    //                     //                     tr.appendChild(tderror);

    //                     //                     var parent = document.getElementById('listoflogs');
    //                     //                     parent.appendChild(tr);

    //                     //                     $(".filesnames").on("click",function(){
    //                     //                         document.getElementById('slh1selector').innerHTML = '';
    //                     //                         var commandfor = $(this).attr('data');
    //                     //                         sync_custom_command(commandfor);
    //                     //                         var h1 = document.createElement('h3');
    //                     //                         var div = document.getElementById('slh1selector');
    //                     //                         var node = document.createTextNode(commandfor);
    //                     //                         h1.appendChild(node);
    //                     //                         div.appendChild(h1);
    //                     //                     });
    //                     //                 }
    //                     //             }
    //                     //             $('body').trigger('processStop');
    //                     //         }
    //                     //     }else if(data_return['function'] === 'showlogfilecontent'){

    //                     //         var table = document.getElementById('listoflogs');
    //                     //         var trs = table.getElementsByClassName("filesnamestr");

    //                     //         for (var i = 0; i < trs.length; i++) {
    //                     //             trs[i].addEventListener("click", function() {
    //                     //                 var current = document.getElementsByClassName("table-active");
    //                     //                 if (current.length > 0) {
    //                     //                     current[0].className = current[0].className.replace("table-active", "");
    //                     //                 }
    //                     //                 this.className += " table-active";
    //                     //             });
    //                     //         }
    //                     //         $('body').trigger('processStop');
    //                     //         document.getElementById('showlog').innerHTML = data_return['content'];
    //                     //         //avisos de error
    //                     //         if(data_return['lines']>=1){
    //                     //             var listed = document.getElementById('sllisted');
    //                     //                 listed.innerHTML = data_return['lines']+ ' Lines' ;
    //                     //                 listed.classList.add("alert");
    //                     //                 listed.classList.add("alert-info");
    //                     //             var faicon = document.createElement('i');
    //                     //                 faicon.setAttribute('class','fas fa-info mar-10');
    //                     //                 listed.insertBefore(faicon,listed.childNodes[0]);

    //                     //         }else{
    //                     //             var listed = document.getElementById('sllisted');
    //                     //                 listed.innerHTML = '';
    //                     //                 listed.classList.remove("alert");
    //                     //                 listed.classList.remove("alert-info");
    //                     //         }
    //                     //         if(data_return['warnings']>=1){
    //                     //             var warning = document.getElementById('slwarnings');
    //                     //                 warning.innerHTML = data_return['warnings']+ ' Warnings';
    //                     //                 warning.classList.add("alert");
    //                     //                 warning.classList.add("alert-warning");
    //                     //                 warning.setAttribute('onclick',"window.location.href=\"#idwarning0\"");
    //                     //             var faicon = document.createElement('i');
    //                     //                 faicon.setAttribute('class','fas fa-exclamation-triangle mar-10');
    //                     //                 warning.insertBefore(faicon,warning.childNodes[0]);

    //                     //         }else{
    //                     //             var warning = document.getElementById('slwarnings');
    //                     //                 warning.innerHTML = '';
    //                     //                 warning.classList.remove("alert");
    //                     //                 warning.classList.remove("alert-warning");
    //                     //         }
    //                     //         if(data_return['errors']>=1){
    //                     //             var errors = document.getElementById('slerrors');
    //                     //                 errors.innerHTML = data_return['errors']+ ' Errors';
    //                     //                 errors.classList.add("alert");
    //                     //                 errors.classList.add("alert-danger");
    //                     //                 errors.setAttribute('onclick',"window.location.href=\"#iderror0\"");
    //                     //             var faicon = document.createElement('i');
    //                     //                 faicon.setAttribute('class','fas fa-times mar-10');
    //                     //                 errors.insertBefore(faicon,errors.childNodes[0]);
    //                     //         }else{
    //                     //             var errors = document.getElementById('slerrors');
    //                     //                 errors.innerHTML = '';
    //                     //                 errors.classList.remove("alert");
    //                     //                 errors.classList.remove("alert-danger");
    //                     //         }
    //                     //     }
    //                     // }else{
    //                     //     showMessage(data_return['message_type'],data_return['content']);
    //                     //     clear_message_status();
    //                     // }
    //                 }).success(function (data_return) {
    //                     console.log('success');
    //                 }).fail(function (data_return) {
    //                     console.log('Ajax connection error: ');
    //                     console.log(data_return);
    //                 }).always(function (){
    //                     // $('body').trigger('processStop');
    //                 });
    //         }
    //         function files_for_delete(command) {
    //             $('body').trigger('processStart');
    //             $.ajax({
    //                 method: "POST",
    //                 url: "<?php echo $block->getUrl('synccatalog/ajax/deletelogs'); ?>",
    //                 data: {'logfilesfordelete':command},
    //                 dataType: "json"
    //             }).done(function (data_return) {
    //                 document.getElementById('listoflogs').innerHTML = '';
    //                 document.getElementById('showlog').innerHTML = '';
    //                 //null info
    //                 var listed = document.getElementById('sllisted');
    //                 listed.innerHTML = '';
    //                 listed.classList.remove("alert");
    //                 listed.classList.remove("alert-info");
    //                 //null warnings
    //                 var warning = document.getElementById('slwarnings');
    //                 warning.innerHTML = '';
    //                 warning.classList.remove("alert");
    //                 warning.classList.remove("alert-warning");
    //                 //null errors
    //                 var errors = document.getElementById('slerrors');
    //                 errors.innerHTML = '';
    //                 errors.classList.remove("alert");
    //                 errors.classList.remove("alert-danger");
    //                 document.getElementById('slh1selector').innerHTML = '';
    //                 if(data_return['message_type'] === 'success'){
    //                     $('body').trigger('processStop');
    //                     sync_custom_command('showlogfiles');
    //                 }
    //             }).fail(function (data_return) {
    //                 console.log('Ajax connection error delete logs');
    //                 clear_message_status();
    //             });
    //         }
    //         $("#selectall").on("click",function(){
    //             var aa = document.querySelectorAll("input[type=checkbox]");
    //             var first = true;
    //             for (var i = 0; i < aa.length; i++){
    //                 first = aa[i].checked;
    //                 if(first === false ){
    //                     aa[i].checked = true;
    //                 }else{
    //                     aa[i].checked = false;
    //                 }
    //             }
    //         });
    //         function showMessage(type = 'success', message) {
    //             if (document.contains(document.getElementById("messages"))) {
    //                 document.getElementById("messages").remove();
    //             }
    //             var elm = document.createElement('div');
    //             elm.setAttribute('id', 'messages');
    //             var subdiv = document.createElement('div');
    //             subdiv.setAttribute('class', 'messages');

    //             var submessage = document.createElement('div');
    //             submessage.setAttribute('class', 'message message-' + type + ' ' + type);

    //             var subdivmessage = document.createElement('div');
    //             subdivmessage.setAttribute('data-ui-id', 'messages-message-' + type);

    //             var node = document.createTextNode(message);

    //             subdivmessage.appendChild(node);
    //             submessage.appendChild(subdivmessage);
    //             subdiv.appendChild(submessage);
    //             elm.appendChild(subdiv);

    //             var parent = document.getElementById('anchor-content');
    //             parent.insertBefore(elm, parent.lastChild);
    //         }
    //         function clear_message_status() {
    //             var timeout = setTimeout(function () {
    //                 if (document.contains(document.getElementById("messages"))) {
    //                     document.getElementById("messages").remove();
    //                 }
    //                 clearTimeout(timeout);
    //             }, 7000);
    //         }
    //         $(".buttonscommandexecuter").on("click",function(){
    //              var command = this.name;
    //              console.log('command en buttonscommandexecuter: '+command);
    //             // sync_custom_command('showlogfiles');
    //              if(command === 'deletelogfile'){
    //                  var  array = [];
    //                  var checkboxes = document.querySelectorAll('input[type=checkbox]:checked');
    //                  for (var i = 0; i < checkboxes.length; i++) {
    //                      array.push(checkboxes[i].value)
    //                  }
    //                  if(array.length >=1){
    //                      files_for_delete(array);
    //                  }
    //              }else{
    //                  sync_custom_command(command);
    //              }
    //          });

    //       //wait until the last element (.payment-method) being rendered
    //     //   var existCondition = setInterval(function() {
    //     //    if ($('.buttonscommandexecuter').length) { 
    //     //     clearInterval(existCondition);
    //     //     runMyFunction();
    //     //    }
    //     //   }, 100);

    //     // function runMyFunction(){
            
    //     //     console.log("terminado de cargar");
    //     //     sync_custom_command('showlogfiles');

    //     // }
    //     console.log('hola :)');

    //     }); 
    //  }); 

    require([
          'jquery',
          // 'showdebbug'
          ], function($){
              $(document).ready(function() {
                   console.log('hola desde showdebbug phtml');
                   // var showdebbug_url_phtml = "<?php echo $block->getUrl('synccatalog/ajax/showdebbug'); ?>";
                   // console.log('showdebbug_url_phtml: '+showdebbug_url_phtml);
                   // console.log('showdebbug_url_phtml_head2: '+showdebbug_url_phtml_head);
              });
          });

</script>
</body>

<!-- http://217.182.82.204/dev_magento231/admin/synccatalog/ajax/showdebbug/key/794c0cc22668b081cd338f7beb558edf6ac03b4341473f789a8301699392aa35/

http://217.182.82.204/dev_magento231/admin/synccatalog/ajax/showdebbug/key/794c0cc22668b081cd338f7beb558edf6ac03b4341473f789a8301699392aa35/

http://217.182.82.204/dev_magento231/admin/synccatalog/ajax/showdebbug/key/794c0cc22668b081cd338f7beb558edf6ac03b4341473f789a8301699392aa35/ -->